// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrclhuqctajxaqcontau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyY2xodXFjdGFqeGFxY29udGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDQ1ODUsImV4cCI6MjA2MTc4MDU4NX0.N-RAacTPP5Oz2JLhYw2q11Gtei1TwirUW0PhDpmzFRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);